'use client';
import { useState } from 'react';
import { BriefcaseBusiness, Check, EyeOff, FileCheck2, LockKeyhole, Scale, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import evidence from '@/data/evidence.json';

const claims = [
  { id:'bounded', label:'RESPALDADA', tone:'supported', text:'Identificó 8 de 10 errores en esta muestra simulada de CFDI.', reason:'Se limita al resultado observado, la tarea y sus condiciones.' },
  { id:'ready', label:'SOBREAFIRMACIÓN', tone:'overclaim', text:'Está lista para trabajar de forma independiente como auxiliar contable.', reason:'Una tarea simulada no demuestra desempeño laboral general ni trabajo independiente.' },
  { id:'potential', label:'VIOLACIÓN DE SOMBRA', tone:'shadow', text:'Tiene alto potencial contable y una empleabilidad de 82/100.', reason:'ProofGuard prohíbe convertir evidencia en potencial o puntajes de empleabilidad.' },
];

export default function Home(){
 const [selected,setSelected]=useState<string[]>([]); const [hidden,setHidden]=useState(false); const [challenge,setChallenge]=useState(''); const [underReview,setUnderReview]=useState(false); const [expires,setExpires]=useState(evidence.expiresAt); const [view,setView]=useState<'candidate'|'employer'>('candidate'); const [displayClaims,setDisplayClaims]=useState(claims); const [analysisLabel,setAnalysisLabel]=useState('ANÁLISIS DE IA SIMULADO'); const [analyzing,setAnalyzing]=useState(false); const [analysisError,setAnalysisError]=useState('');
 const shared=!hidden&&!underReview&&selected.includes('bounded')&&new Date(expires+'T23:59:59')>=new Date();
 const toggle=(id:string,tone:string)=>{if(tone!=='supported'||hidden||underReview)return;setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])};
 const saveChallenge=()=>{if(challenge.trim().length<5)return;setUnderReview(true);setSelected([])};
 const analyze=async()=>{setAnalyzing(true);setAnalysisError('');try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({evidence,claims:claims.map(c=>c.text)})});if(!response.ok)throw new Error();const data=await response.json() as {label?:unknown;results?:unknown};if(typeof data.label!=='string'||!Array.isArray(data.results)||data.results.length!==claims.length)throw new Error();setAnalysisLabel(data.label);setDisplayClaims(data.results.map((item:unknown,i:number)=>{if(!item||typeof item!=='object')throw new Error();const r=item as Record<string,unknown>;if(typeof r.claim!=='string'||typeof r.classification!=='string'||typeof r.reason!=='string')throw new Error();return {...claims[i],text:r.claim,reason:r.reason,tone:r.classification==='SUPPORTED'?'supported':r.classification==='OVERCLAIM'?'overclaim':'shadow',label:r.classification==='SUPPORTED'?'RESPALDADA':r.classification==='OVERCLAIM'?'SOBREAFIRMACIÓN':'VIOLACIÓN DE SOMBRA'}}));}catch{setAnalysisError('No pudimos analizar ahora. Las reglas de seguridad siguen activas.');}finally{setAnalyzing(false)}};
 return <main>
  <header className="topbar"><a className="brand" href="#inicio"><ShieldCheck/> ProofGuard</a><p>La evidencia describe una tarea, no decide tu futuro.</p><div className="view-switch" aria-label="Cambiar vista"><button className={view==='candidate'?'active':''} onClick={()=>setView('candidate')}>Candidata</button><button className={view==='employer'?'active':''} onClick={()=>setView('employer')}>Empleador</button></div></header>
  <div className="sim-banner">DATOS SIMULADOS · PERSONA FICTICIA · ANÁLISIS DE IA SIMULADO</div>
  {view==='employer'?<section className="employer-view"><span className="eyebrow">Vista previa del empleador · Simulada</span><h1>Evidencia que Sofía decidió compartir.</h1>{shared?<article className="share-card"><div className="share-head"><FileCheck2/><div><strong>{evidence.assessment}</strong><span>{evidence.candidate.displayName} · Registro ficticio</span></div></div><blockquote>“{claims[0].text}”</blockquote><dl className="facts"><div><dt>Condiciones</dt><dd>{evidence.conditions}</dd></div><div><dt>Asistencia de IA</dt><dd>{evidence.aiAssistance}</dd></div><div><dt>Vigente hasta</dt><dd>{expires}</dd></div></dl><p className="plain-note">Procedencia: {evidence.provenance} · Rúbrica {evidence.rubricVersion}. {evidence.limitations}</p></article>:<div className="empty"><EyeOff/><h2>No hay evidencia compartida</h2><p>Esto no significa que falte o haya fallado una evaluación. La candidata no ha compartido evidencia vigente.</p></div>}<Button className="primary-button" onClick={()=>setView('candidate')}>Volver a controles</Button></section>:
  <><section className="intro" id="inicio"><div><span className="eyebrow">Revisión de evidencia</span><h1>Lo que hiciste, sin convertirlo en quién eres.</h1><p>Revisa qué afirmaciones sí están respaldadas, corrige el registro y decide exactamente qué puede ver un empleador.</p></div><div className="control-note"><LockKeyhole/><div><strong>Tú tienes el control</strong><span>Nada se comparte hasta que lo eliges.</span></div></div></section>
  <section className="workspace"><article className="evidence-card"><div className="section-heading"><div><span className="eyebrow">Evidencia principal</span><h2>{evidence.assessment}</h2></div><span className="pill neutral">SIMULADA</span></div><div className="candidate"><span className="avatar">SM</span><div><strong>{evidence.candidate.displayName}</strong><span>{evidence.candidate.age} años · {evidence.role}</span></div><div className="score"><small>Resultado simulado</small><b>{evidence.result.correct}<em>/{evidence.result.total}</em></b></div></div><p className="task">{evidence.task}</p><dl className="facts"><div><dt>Asistencia de IA</dt><dd>{evidence.aiAssistance}</dd></div><div><dt>Procedencia</dt><dd>{evidence.rubricVersion}</dd></div><div><dt>Caducidad</dt><dd>{expires}</dd></div></dl><div className="limit"><Scale/><p><strong>Límite de esta evidencia</strong>{evidence.limitations}</p></div></article>
  <section className="claims-panel"><div className="section-heading"><div><span className="eyebrow">Lenguaje bajo revisión</span><h2>Elige solo lo respaldado</h2></div><Button variant="outline" onClick={analyze} disabled={analyzing}>{analyzing?'Analizando…':'Analizar con IA'}</Button></div><p className="analysis-mode">{analysisLabel}</p>{analysisError&&<p className="analysis-error" role="alert">{analysisError}</p>}<div className="claim-list">{displayClaims.map(c=><button type="button" aria-pressed={selected.includes(c.id)} disabled={c.tone!=='supported'||hidden||underReview} onClick={()=>toggle(c.id,c.tone)} className={`claim ${c.tone} ${selected.includes(c.id)?'selected':''}`} key={c.id}><FileCheck2/><span><b>{c.text}</b><small>{c.reason}</small></span><span className="pill">{selected.includes(c.id)?'ELEGIDA':c.label}</span></button>)}</div><p className="plain-note">Solo una afirmación respaldada puede compartirse. Las demás permanecen bloqueadas.</p></section></section>
  <section className="control-panel"><div><label htmlFor="expiry">La autorización caduca</label><Input id="expiry" type="date" value={expires} min="2026-09-07" onChange={e=>setExpires(e.target.value)}/></div><div className="challenge-box"><label htmlFor="challenge">¿Algo está mal? Corrige o impugna</label><Textarea id="challenge" maxLength={500} value={challenge} onChange={e=>setChallenge(e.target.value)} placeholder="Explica qué dato necesita revisión…"/><Button variant="outline" onClick={saveChallenge} disabled={challenge.trim().length<5}>Enviar a revisión</Button></div><div className="status-box"><b>Estado de compartir</b><p>{underReview?'En revisión: el empleador no ve el puntaje, etiquetas ni tu nota.':hidden?'Todo oculto: el empleador no ve puntaje, etiquetas ni correcciones.':selected.length?'Solo 1 afirmación respaldada está lista; nada se publica al abrir la vista previa.':'Nada seleccionado. El empleador no ve puntaje ni etiquetas.'}</p><div><Button variant="outline" onClick={()=>{setHidden(!hidden);setSelected([])}}><EyeOff/>{hidden?'Permitir seleccionar de nuevo':'Ocultar todo al empleador'}</Button><Button className="primary-button" disabled={!shared} onClick={()=>setView('employer')}><BriefcaseBusiness/>Vista previa (no publica)</Button></div></div></section>
  {underReview&&<output className="review-notice"><Check/>Corrección enviada localmente. Este prototipo no guarda datos; al recargar se elimina.</output>}</>}
 </main>;
}
